version: "3.8"

services:
  db:
    image: mysql:8
    container_name: personal_dashboard_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal-dashboard
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  backend:
    build: ./personal-dashboard-be
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/personal-dashboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  frontend:
    build: ./personal-dashboard-fe
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  db-data:

  # docker-compose up -d            start everything
  # docker-compose down             stop everything
  # docker-compose up -d --build backend   rebuild after code change
  # docker-compose up -d --build frontend
  # docker-compose up -d --build db